name: duetrack
description: A Flutter application for tracking courses and assignments.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.1           # For state management
  intl: ^0.18.1              # For date formatting
  table_calendar: ^3.0.9     # For calendar view
  flutter_local_notifications: ^18.0.1  # For reminders
  timezone: ^0.9.2           # For timezone support
  uuid: ^3.0.7               # For generating unique IDs
  percent_indicator: ^4.2.2
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, uncomment the following:
  # assets:
  #   - assets/images/

  # To add custom fonts to your application, uncomment the following:
  # fonts:
  #   - family: YourCustomFont
  #     fonts:
  #       - asset: fonts/YourCustomFont-Regular.ttf
  #       - asset: fonts/YourCustomFont-Bold.ttf
  #         weight: 700